### ISSUE TITLE
Could not find gem 'spree_backend (~> 3.1.0.beta) x86-mingw32', which is required by gem 'spree_mail_settings (>= 0) x86-mingw32', in any of the sources.

### ISSUE THREAD

**Issue by vike27** [spree-contrib/spree_mail_settings#11]
I am running spree 3-0-stable

I don't get why it is asking for spree 3.1.0.beta? That is not even out yet... and I don't want to use a bleeding edge version. Any way I can make this work?

Is there maybe an older/stable version of the spree_mail_settings gem that I can use that is compatible with spree 3-0-stable?

This was my error message:

    Could not find gem 'spree_backend (~> 3.1.0.beta) x86-mingw32', which is
    required by gem 'spree_mail_settings (>= 0) x86-mingw32', in any of the sources.

**Comment by futhr** [comment]
Hi @vike27 Point to the correct branch in your Gemfile and then run bundle update.
