### ISSUE TITLE
Test emails works great but the real ones not

### ISSUE THREAD

**Issue by mbajur** [spree-contrib/spree_mail_settings#13]
Hello!
I'm trying to use spree_mail_settings in my spree instance but i have one major problem with that - the test email is working as it should but the actual mails sent by the app during checkout/payment/shipment process are being sent properly. There are no any errors nor warnings, console log says that email has been sent but it's not (i can say that for 100% because it is not present in Mandrill's outbound page while the test ones are there).

I'm on master branch of spree and spree_mail_settings

Thanks in advance.

**Comment by kurapatijayaram** [comment]
Hi,
    Even test mail is not working fine for me :-(

**Comment by igorkrup** [comment]
Same for me
I'm getting an error in admin:
Test Mail error: 550 Incorrect sender information in header.
And the logs says that in header I have:
From: spree@example.com
no matter what is defined in "Send mail as" field

**Comment by kurapatijayaram** [comment]
Hi,
    For me it's working great. The only mistake I made was I didn't enabled email delivery . :-)

**Comment by fuzzytern** [comment]
@kurapatijayaram can you be more explicit on what you mean by "enabling email delivery"?

**Comment by kurapatijayaram** [comment]
In admin panel under mail settings section , you can see an check box option mentioning enable mail delivery enable that and send test mail ... It will work.

**Comment by igorkrup** [comment]
Ok, so my problem was that mails_from should be defined in general spree settings, not in this gem settings. From now i have no idea what is "send mail as" option for (and does it even work?)

**Comment by kurapatijayaram** [comment]
Send mail_as is just from address for end user ... Just display logic it won't deliver through that mail id

**Comment by igorkrup** [comment]
That was I thought but I'm pretty sure it is not working.

**Comment by kurapatijayaram** [comment]
But for me it's working fine ... Are u getting any error for that ??

**Comment by kurapatijayaram** [comment]
Hi @igorkrup 
                Sorry for my previous reply. By default mail_as wont work, we need to modify base_mailer class in spree core. Add the following decorator in your app. It will work.

module Spree
	BaseMailer.class_eval do
		def from_address
			Spree::Config[:mails_from] || Spree::Store.current.mail_from_address
		end
	end
end

**Comment by aishmita-aggarwal** [comment]
Persists on master. Looking into it.

**Comment by aishmita-aggarwal** [comment]
@mbajur Could you please share your settings for smtp?

**Comment by mbajur** [comment]
@aishmita-aggarwal sorry, i'm not able to do that right now. But, anyway, it seems that you resolved it.
