### ISSUE TITLE
Send Testmail Text Broken

### ISSUE THREAD

**Issue by BenMorganIO** [spree-contrib/spree_mail_settings#2]
After installing into an existing Spree application via openjaf's fork for Spree 2.3.0.beta applications, I discovered this issue. See image below.

The Testmail button appears to be broken.

![screen shot 2014-05-18 at 8 57 32 pm](https://cloud.githubusercontent.com/assets/3117356/3009865/dd00bef4-df09-11e3-9d64-e8f8f50c963b.png)

**Comment by futhr** [comment]
Hi @BenMorganIO and @iRonin, I have created a `2-3-stable` branch and applied the translation fix, you welcome to try it out.

**Comment by iRonin** [comment]
Thanks for the info @futhr !
