### ISSUE TITLE
Could not find gem 'spree_backend (~> 3.1.0.beta)', which is required by gem 'spree_mail_settings', in any of the sources.

### ISSUE THREAD

**Issue by saroar** [spree-contrib/spree_mail_settings#23]
Bundler could not find compatible versions for gem "spree_backend":
  In Gemfile:
    spree_mail_settings was resolved to 2.2.0, which depends on
      spree_backend (~> 3.1.0.beta)

Could not find gem 'spree_backend (~> 3.1.0.beta)', which is required by gem 'spree_mail_settings', in any of the sources.

source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.15'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

gem 'solidus'
gem 'solidus_auth_devise'
gem 'spree_mail_settings', github: 'spree-contrib/spree_mail_settings', branch: 'master'

**Comment by aishmita-aggarwal** [comment]
@saroar spree_backend is a dependency for spree_multi_currency.

**Comment by saroar** [comment]
thanks i don't use anymore spree i create my own shop app with rails :)
