### ISSUE TITLE
Facing issue SocketError (getaddrinfo: Name or service not known)

### ISSUE THREAD

**Issue by dinshawr** [spree-contrib/spree_mail_settings#31]
Hello I have included given gem in my gemfile:

    gem 'spree_mail_settings', github: 'spree-contrib/spree_mail_settings', branch: '3-0-stable'

and further done settings in spree-admin in configuration < Mail method Settings
[![enter image description here][1]][1]

  [1]: http://i.stack.imgur.com/KpxTL.png

When I place order it gives me error 

> 2016-05-10T07:16:32.164733+00:00 app[web.1]: 
> 2016-05-10T07:16:32.164734+00:00 app[web.1]: [ActiveJob]
> [ActionMailer::DeliveryJob] [9526835c-d5e7-4434-b716-a98b68b75da1]
> Performed ActionMailer::DeliveryJob from Inline(mailers) in 471.29ms
> 2016-05-10T07:16:32.164735+00:00 app[web.1]: Completed 500 Internal
> Server Error in 1395ms (ActiveRecord: 179.9ms)
> 2016-05-10T07:16:32.168574+00:00 app[web.1]: 
> 2016-05-10T07:16:32.168583+00:00 app[web.1]: SocketError (getaddrinfo:
> Name or service not known): 2016-05-10T07:16:32.168583+00:00
> app[web.1]:   vendor/ruby-2.2.4/lib/ruby/2.2.0/net/smtp.rb:541:in
> `initialize' 2016-05-10T07:16:32.168584+00:00 app[web.1]:  
> vendor/ruby-2.2.4/lib/ruby/2.2.0/net/smtp.rb:541:in `open'
> 2016-05-10T07:16:32.168584+00:00 app[web.1]:  
> vendor/ruby-2.2.4/lib/ruby/2.2.0/net/smtp.rb:541:in `tcp_socket'
> 2016-05-10T07:16:32.168585+00:00 app[web.1]:  
> vendor/ruby-2.2.4/lib/ruby/2.2.0/net/smtp.rb:551:in `block in
> do_start' 2016-05-10T07:16:32.168585+00:00 app[web.1]:  
> vendor/ruby-2.2.4/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
> 2016-05-10T07:16:32.168586+00:00 app[web.1]:  
> vendor/ruby-2.2.4/lib/ruby/2.2.0/timeout.rb:98:in `call'
> 2016-05-10T07:16:32.168586+00:00 app[web.1]:  
> vendor/ruby-2.2.4/lib/ruby/2.2.0/timeout.rb:98:in `timeout'
> 2016-05-10T07:16:32.168587+00:00 app[web.1]:  
> vendor/ruby-2.2.4/lib/ruby/2.2.0/net/smtp.rb:550:in `do_start'
> 2016-05-10T07:16:32.168587+00:00 app[web.1]:  
> vendor/ruby-2.2.4/lib/ruby/2.2.0/net/smtp.rb:520:in `start'
> 2016-05-10T07:16:32.168587+00:00 app[web.1]:  
> vendor/bundle/ruby/2.2.0/gems/mail-2.6.4/lib/mail/network/delivery_methods/smtp.rb:113:in `deliver!' 2016-05-10T07:16:32.168588+00:00 app[web.1]:  
> vendor/bundle/ruby/2.2.0/bundler/gems/spree_mail_settings-d416a1e35589/lib/spree/core/mail_method.rb:8:in
> `deliver!' 2016-05-10T07:16:32.168588+00:00 app[web.1]:  

Please guide me why I am facing this issue and what settings are required.

**Comment by samar-mishra** [comment]
I have answered this here;

http://stackoverflow.com/a/37134253/1776255

**Comment by dinshawr** [comment]
Thanks samar its working correctly now :)
