### ISSUE TITLE
'Test Mail error: no implicit conversion of nil into Hash' error

### ISSUE THREAD

**Issue by justinemar** [spree-contrib/spree_mail_settings#41]
Sending a test mail from the admin mail method settings interface shows this error
`Test Mail error: no implicit conversion of nil into Hash`
SMTP SETTING
SMTP DOMAIN :gmail.com
SMTP MAIL HOST: smtp.gmail.com
SMTP PORT: 465
Connection : SSL
auth type: login
username: my account email
password: my account password.

*Different port and connection gets different error*
`Test Mail error: SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol`
SMTP SETTING
SMTP DOMAIN :gmail.com
SMTP MAIL HOST: smtp.gmail.com
SMTP PORT: 587
Connection : TLS
auth type: login
username: my account email
password: my account password.

**Comment by APohio** [comment]
I am getting this exact same error. Spent about 8 hours on it and cannot figure it out.


I even tried a completely fresh install and it does the same thing. Only ever on production though, development seems to work fine.

If anybody figures this out I would be extremely appreciative.

**Comment by justinemar** [comment]
I'm using spree 3.3.0 will the downgrade cost any problem to my store?, i haven't done much customization tho just the logo and added some roles.

**Comment by justinemar** [comment]
Heh, it suddenly worked i have no idea i was just trying my luck if it'll work and it did 👍
