### ISSUE TITLE
spree 2-4-stable

### ISSUE THREAD

**Issue by kruby** [spree-contrib/spree_mail_settings#5]
How to install spree_mail_settings with spree 2-4-stable?
When trying to bundle it says:
In Gemfile:
    spree_mail_settings (>= 0) ruby depends on
      spree_backend (~> 2.2.0) ruby
    spree (>= 0) ruby depends on
      spree_backend (2.4.0.rc3)

**Comment by TomGroombridge** [comment]
Any idea when spree_mail_settings will be available on 2-4 stable?

**Comment by thiyagarajan** [comment]
Any idea when spree_mail_settings will be available on 2-4 stable?

**Comment by futhr** [comment]
Hi all, just created a `2-4-stable` branch based on `2-3-stable` that you welcome to try out.

**Comment by TomGroombridge** [comment]
@futhr  thank you
