### ISSUE TITLE
compatible error with spree_auth_devise > 4.0

### ISSUE THREAD

**Issue by samuelasselin** [spree-contrib/spree_mail_settings#52]
Can someone help me to find a fix. Trying to bundle install with : 
"gem 'spree_mail_settings', github: 'spree-contrib/spree_mail_settings" ,
in my gem file on spree version > 4.0 !

**I got this compatible version error:**
Bundler could not find compatible versions for gem "spree_auth_devise":
  In snapshot (Gemfile.lock):
    spree_auth_devise (= 4.0.0)
  In Gemfile:
    spree_auth_devise (~> 4.0)
    **spree_mail_settings was resolved to 3.3.0, which depends on
      spree_auth_devise (>= 3.1.0, < 4.0)**

**Gem I use :** 
Using spree_core 4.0.3
Using spree_api 4.0.3
Using spree_backend 4.0.3
Using spree_cmd 4.0.3
Using spree_frontend 4.0.3
Using spree_sample 4.0.3
Using spree 4.0.3
Using spree_extension 0.0.9
Using spree_auth_devise 4.0.0
Using spree_gateway 3.6.7
Using spree_social 3.3.2

Thanks

**Comment by Ghaithdabash** [comment]
Was this issue fixed ?
