### ISSUE TITLE
Test emails are not delivered and always return an error

### ISSUE THREAD

**Issue by jtgeibel** [spree-contrib/spree_mail_settings#8]
The API for Spree::TestMailer.test_email changed in 4.2.0.rc1.  From spree/spree@6518e338 it looks like the function previously accpeted either a user object or a user ID.  Now, the email address should be passed. 

I believe this affects the master, 3-0-stable, and 2-4-stable branches.

**Comment by futhr** [comment]
Thank you @jtgeibel for supply the actual reference concerning this, it has been applied to `2-4-stable` and `master` branch.
